{
  pkgs,
  config,
  lib,
  ...
}:

{
  config.systemd.services.cloudflared-remote = {
    description = "Cloudflare Tunnel (Remote Managed) for Lairland HQ";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    serviceConfig = {
      # Use an EnvironmentFile to securely load the TUNNEL_TOKEN generated by agenix
      EnvironmentFile = "/run/agenix/cftunnels-rtdev-secrets";
      # The run command automatically picks up the TUNNEL_TOKEN environment variable
      ExecStart = "${pkgs.cloudflared}/bin/cloudflared tunnel --no-autoupdate run";
      Restart = "always";
      RestartSec = "5s";
    };
  };

  config.systemd.services.cloudflared-remote-recaptime-dev = {
    description = "Cloudflare Tunnel (Remote Managed) for Recap Time Squad";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    serviceConfig = {
      # Use an EnvironmentFile to securely load the TUNNEL_TOKEN generated by agenix
      EnvironmentFile = "/run/agenix/cftunnels-rtdev-secrets";
      # The run command automatically picks up the TUNNEL_TOKEN environment variable
      ExecStart = "${pkgs.cloudflared}/bin/cloudflared tunnel --no-autoupdate run";
      Restart = "always";
      RestartSec = "5s";
    };
  };
}
