name: Nix Flake Builds

on:
  schedule:
    - cron: "30 6 * * 5"
  push:
    branches: [main]

permissions:
  contents: write
  actions: write

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Deterinate Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - name: Update flake
        run: |
          echo ::group::Updating lockfile
          nix flake update
          echo ::endgroup::

          echo ::group::Metadata
          nix flake metadata
          echo ::endgroup::

      - name: Commit and push changes
        run: |
          git config --global user.name "RecapTimeBot"
          git config --global user.email "recaptimebot@gmail.com"
          git add flake.lock
          git commit -m "Update flake.lock [skip-ci]" || echo "No changes to commit"
          git push
  build-iso:
    concurrency:
      cancel-in-progress: false
      group: recoverykit-iso-builds
    needs: [update-lockfile]
    name: Build recovery ISO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Deterinate Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true

      - run: nix flake metadata

      - run: |
          mkdir dist
          echo ::group::Building amd64 minimal ISO file
          nix build .#nixosConfigurations.recoverykit-amd64.config.system.build.isoImage --verbose --show-trace
          cp result/iso/*.iso ./dist/ -rv
          echo ::endgroup
      
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-recoverykit-iso
          path: dist